/**
 * Scans public/images/carousel for image files and generates src/data/carouselImages.js.
 * Run before start/build so the carousel shows all images in that folder.
 * Add or remove images in public/images/carousel - no code changes needed.
 */

const fs = require('fs');
const path = require('path');

const CAROUSEL_DIR = path.join(__dirname, '..', 'public', 'images', 'carousel');
const OUTPUT_FILE = path.join(__dirname, '..', 'src', 'data', 'carouselImages.js');

const IMAGE_EXT = /\.(jpg|jpeg|png|gif|webp)$/i;

function naturalSort(a, b) {
  const numA = parseInt(a.match(/\d+/)?.[0] || '0', 10);
  const numB = parseInt(b.match(/\d+/)?.[0] || '0', 10);
  if (numA !== numB) return numA - numB;
  return a.localeCompare(b);
}

function generate() {
  if (!fs.existsSync(CAROUSEL_DIR)) {
    fs.writeFileSync(OUTPUT_FILE, `// Auto-generated - no images in public/images/carousel
export const carouselImages = [];
`);
    console.log('Carousel: no folder found, wrote empty list');
    return;
  }

  const files = fs.readdirSync(CAROUSEL_DIR)
    .filter((f) => IMAGE_EXT.test(f))
    .sort(naturalSort);

  const lines = files.map(
    (f) => `  \`\${process.env.PUBLIC_URL || ''}/images/carousel/${f}\``
  );

  const content = `// Auto-generated by scripts/generateCarousel.js - do not edit
// Add/remove images in public/images/carousel - then run npm start or npm run build

export const carouselImages = [
${lines.join(',\n')}
];
`;

  fs.writeFileSync(OUTPUT_FILE, content);
  console.log(`Carousel: generated list of ${files.length} images`);
}

generate();
